use std::env;

const ZSH_HOOK: &str = r#"
# zellij-ssidebar hook for zsh
# Generated by zellij-ssidebar hook zsh
# Chains with existing preexec/precmd hooks

_sidebar_shell_preexec() {
    local cmd="$1"
    [[ -z "$ZELLIJ_SESSION_NAME" ]] && return
    local name="$(basename "$cmd" 2>/dev/null || echo "$cmd")"
    # Strip NixOS wrapper prefixes
    name="$(echo "$name" | sed 's/^__//; s/-wrapped$//')"
    local dir="${TMPDIR:-/tmp/}zellij-$(id -u)/sidebar-shell/$ZELLIJ_SESSION_NAME"
    mkdir -p "$dir"
    echo "$name $(date +%s)" > "$dir/${ZELLIJ_PANE_ID:-0}"
}

_sidebar_shell_precmd() {
    [[ -z "$ZELLIJ_SESSION_NAME" ]] && return
    local dir="${TMPDIR:-/tmp/}zellij-$(id -u)/sidebar-shell/$ZELLIJ_SESSION_NAME"
    rm -f "$dir/${ZELLIJ_PANE_ID:-0}" 2>/dev/null
    # Try to clean up empty session dir
    rmdir "$dir" 2>/dev/null
}

# Chain with existing hooks
preexec_functions+=("_sidebar_shell_preexec")
precmd_functions+=("_sidebar_shell_precmd")
"#;

const BASH_HOOK: &str = r#"
# zellij-ssidebar hook for bash
# Generated by zellij-ssidebar hook bash
# Chains with existing PROMPT_COMMAND / DEBUG trap

_sidebar_shell_preexec() {
    local cmd="$BASH_COMMAND"
    [[ "$cmd" == "$PROMPT_COMMAND" ]] && return
    [[ -z "$ZELLIJ_SESSION_NAME" ]] && return
    local name="$(basename "$cmd" 2>/dev/null || echo "$cmd")"
    # Strip NixOS wrapper prefixes
    name="$(echo "$name" | sed 's/^__//; s/-wrapped$//')"
    local dir="${TMPDIR:-/tmp/}zellij-$(id -u)/sidebar-shell/$ZELLIJ_SESSION_NAME"
    mkdir -p "$dir"
    echo "$name $(date +%s)" > "$dir/${ZELLIJ_PANE_ID:-0}"
}

_sidebar_shell_precmd() {
    [[ -z "$ZELLIJ_SESSION_NAME" ]] && return
    local dir="${TMPDIR:-/tmp/}zellij-$(id -u)/sidebar-shell/$ZELLIJ_SESSION_NAME"
    rm -f "$dir/${ZELLIJ_PANE_ID:-0}" 2>/dev/null
    rmdir "$dir" 2>/dev/null
}

# Chain with existing DEBUG trap
trap '_sidebar_shell_preexec' DEBUG

# Chain with existing PROMPT_COMMAND
if [[ -n "$PROMPT_COMMAND" ]]; then
    PROMPT_COMMAND="${PROMPT_COMMAND}; _sidebar_shell_precmd"
else
    PROMPT_COMMAND="_sidebar_shell_precmd"
fi
"#;

fn print_usage() {
    eprintln!("Usage: zellij-ssidebar hook <zsh|bash>");
    eprintln!("");
    eprintln!("  zsh   -- print shell hook for zsh");
    eprintln!("  bash  -- print shell hook for bash");
    eprintln!("");
    eprintln!("Add to your shell config:");
    eprintln!("  eval \"$(zellij-ssidebar hook zsh)\"");
    eprintln!("  eval \"$(zellij-ssidebar hook bash)\"");
}

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 3 {
        print_usage();
        std::process::exit(1);
    }

    if args[1] != "hook" {
        print_usage();
        std::process::exit(1);
    }

    match args[2].as_str() {
        "zsh" => println!("{}", ZSH_HOOK),
        "bash" => println!("{}", BASH_HOOK),
        _ => {
            eprintln!("Unknown shell: {}. Use zsh or bash.", args[2]);
            std::process::exit(1);
        }
    }
}
